package xerial.chroniker

// This class will be generated by `ck import td:sample_dataset` command:
object sample_dataset
{
  class Nasdaq
  {
    val time = Column[Nasdaq, Long]("time")
    val symbol = Column[Nasdaq, String]("symbol")
    val open = Column[Nasdaq, Double]("open")
    val volume = Column[Nasdaq, String]("volume")
    val high = Column[Nasdaq, Double]("high")
    val low = Column[Nasdaq, Double]("low")
    val close = Column[Nasdaq, Double]("close")
  }

  val nasdaq = new Frame[Nasdaq]

}

import sample_dataset._

object Example
{
  // SELECT count(*) FROM nasdaq
  def dataCount = nasdaq.size

  // SELECT time, close FROM nasdaq WHERE symbol = 'APPL'
  def appleStock = nasdaq.filter(_.symbol is "APPL").select(_.time, _.close)

  // You can use a raw SQL statement as well:
  def appleStockSQL = sql"SELECT time, close FROM nasdaq where symbol = 'APPL'".as[Nasdaq]

  // SELECT time, close FROM nasdaq WHERE symbol = 'APPL' LIMIT 10
  appleStock.limit(10).print

  appleStockSQL.limit(5).print

  // time-column based filtering
  def recentAppleStock = appleStock.between(SCHEDULED_TIME, SCHEDULED_TIME + 1.month)

  def multipleResults = {
    Seq("YHOO", "GOOG", "MSFT").map { company =>
      company -> nasdaq
              .filter(_.symbol is company)
              .select(_.time, _.close)
    }
  }

}

object RunningExample {

  val td = new TDExecutor

  Example.recentAppleStock.run(td)
}

